### ISSUE TITLE
리뷰 사항 정리.

### ISSUE THREAD

**Issue by AppleHolic** [wbaek/dataflow#1]
#### 문제가 될 것으로 보이는 상황
1. tenth2 쪽에서 200 ok와 함께 텅 빈 body를 보낸 경우가 종종 발생함 retry를 해야 할 것으로 보임.
2. label또는 데이터의 index를 dataflow에 같이 실어서 보내야 할 듯 한데, 이미지만 보내는 것으로 보임.

#### comment
깔끔하게 되게 잘 짜져 있어서 감탄했어유 ~ 다음에 코딩 할 때 잘 참조하겠습니다. ^^

**Comment by wbaek** [comment]
1. 200 OK이지만 empty body인경우 retry
https://github.com/wbaek/dataflow/commit/b04880332aedb8623e48e72f664e717491228848
2. label데이터는 함께 보내고 있음
https://github.com/wbaek/dataflow/blob/master/dataflow/dataset/ilsvrc.py#L31
@ @
